version: '2'
services:
  web:
    build: ./web
    image: cclweb
    depends_on:
      - mailhog
    environment:
      MAIL_SERVER: mailhog
      MAIL_SERVER_PORT: 1025
      MAIL_AUTHENTICATION: "False"
      DEV_DATABASE_URL: sqlite:////usr/data/web.db
    env_file:
      - settings.env
    links:
      - mailhog
    ports:
      - "5000:5000"
    volumes:
      - "./web:/usr/app"
      - "./db:/usr/data"
    entrypoint:
      - python
      - /usr/app/manage.py
      - runserver
      - "-t"
      - "0.0.0.0"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    expose:
      - "1025"
